title: Sai Swaroop Gali
logo: /assets/Profile.png
description: Data Engineer | AI Engineer | AWS Certified | Microsoft Fabric Certified | Python | SQL | ETL Pipelines | RAG Pipelines | Multi-Agent Systems 🚀📊
#show_downloads: true
#email: Sai-Swaroop.Gali@outlook.com
#location: Koblenz, Germany
theme: jekyll-theme-minimal
